FROM apache/airflow:2.8.1

USER root

RUN apt-get update && \
    apt-get install -y gcc g++ libffi-dev libssl-dev && \
    apt-get clean

USER airflow

RUN pip install --no-cache-dir pandas bids elasticsearch
